title: Nikolay Tsanov - Web Developer
description: A full-stack web developer with experience in Laravel and solid background in frontend development.
# baseurl: "https://ntsanov.com"
baseurl: ""
defaults:
  - scope:
      path: "assets/images"
    values:
      image: true

exclude:
  - Gemfile
  - Gemfile.lock
  - gulpfile.babel.js
  - LICENSE.md
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - src
  - tailwind.config.js
