title: Web Developer
description: A full-stack web developer with experience in Laravel and solid background in frontend development.
# baseurl: "https://ntsanov.com"
baseurl: ""
defaults:
  - scope:
      path: "assets/images"
    values:
      image: true
collections_dir: collections
collections:
  projects:
    output: false
    permalink: "/:collection/:name"
  posts:
    output: true
    permalink: "/posts/:slug"

exclude:
  - Gemfile
  - Gemfile.lock
  - gulpfile.babel.js
  - LICENSE.md
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - src
  - tailwind.config.js

url: "https://ntsanov.com" # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap
markdown: kramdown
highlighter: rouge